### ISSUE TITLE
DDT - Build Model Hangs

### ISSUE THREAD

**Issue by mikew77** [VIDA-NYU/domain_discovery_tool_deprecated#71]
Having created a new domain, tagged pages and terms as relevant and irrelevant, I click on the "Build Model" button to generate training data package for use with ACHE.  The cursor goes busy for a long period (circa 30-45 minutes) and no content is created even when I check in the folders via command line.

This applies to the local development instance v2.8.3 of DDT

**Comment by aecio** [comment]
Hi @mikew77, this should have been fixed in commit 4291a468ee8ca378dafb8ccb79f2a68bf8d3c336. Can you try again using the latest version from the master branch?

**Comment by mikew77** [comment]
Hi Aecio

Thanks for your help; I've left the office for the weekend as I'm gmt +8 but will try as soon as I'm back in the office next week and will let you know. 

Thanks again!

Best regards
Mike

**Comment by mikew77** [comment]
Hi Aecio, still seeing the hang on the build model generation (ran the
process for several hours).  This time however I tested on the docker
deployment (I saw the initial bug on the standalone deployment).  So it may
be the fix hasn't been ported to the docker deployment.  I'll retry and let
you know how it goes.

**Comment by mikew77** [comment]
Apologies, user error from my earlier test.  I tried again by deleting my
clone of the github folder and rebuilt the docker environment (couldn't get
standalone up and running).  The build model is now generating.  Thanks for
your help! :)

**Comment by yamsgithub** [comment]
@mikew77 could you please send me the details of the error you get when you build and run the standalone version?

**Comment by mikew77** [comment]
@yamsgithub sorry; I didn't make a copy of the error message I received.  I think it got through the install process but couldn't launch the environment - so I launched supervisord, but couldn't hit DDT on localhost:8084

I have noticed that even with the docker deployment, I sometimes need to switch browsers to get DDT up and running otherwise I can't hit the app.  I may retest the standalone version and if I get the error will repost here as well; thanks for following up!
